cubesat:
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000

  joint_motor_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
          - joint_RDR_1
          - joint_RDR_2
          - joint_RDR_3
      gains:
          joint_RDR_1: {p: 1, i: 0, d: 1}
          joint_RDR_2: {p: 1, i: 0, d: 1}
          joint_RDR_3: {p: 1, i: 0, d: 1}
          
